package org.fordes.adfs.syntax.classifier;

public enum SeparatorKind {
    UBO_SCRIPTLET_EXCEPTION,
    ADGUARD_SCRIPTLET_EXCEPTION,
    UBO_HTML_EXCEPTION,
    EXTENDED_CSS_EXCEPTION,
    EXTENDED_COSMETIC_EXCEPTION,
    HASH_DOLLAR_EXCEPTION,
    HASH_PERCENT_EXCEPTION,
    ELEMENT_HIDING_EXCEPTION,
    ADGUARD_HTML_EXCEPTION,
    UBO_SCRIPTLET,
    ADGUARD_SCRIPTLET,
    UBO_HTML,
    EXTENDED_CSS,
    EXTENDED_COSMETIC,
    HASH_DOLLAR,
    HASH_PERCENT,
    ELEMENT_HIDING,
    ADGUARD_HTML
}
