application:

  input:

    - name: AdGuard Cookie通知过滤器
      path: https://filters.adtidy.org/android/filters/18_optimized.txt
      type: easylist
      
    - name: AdGuard 弹窗过滤器
      path: https://filters.adtidy.org/android/filters/19_optimized.txt
      type: easylist
      
    - name: AdGuard 移动拦截程序横幅广告的过滤器
      path: https://filters.adtidy.org/android/filters/20_optimized.txt
      type: easylist

    - name: AdGuard 其他恼人广告过滤器
      path: https://filters.adtidy.org/android/filters/21_optimized.txt
      type: easylist

    - name: AdGuard 恼人广告过滤器
      path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt
      type: easylist

    - name: Online Malicious URL Blocklist
      path: https://urlhaus-filter.pages.dev/urlhaus-filter-ag-online.txt
      type: easylist

    - name: AdGuard 小工具过滤器
      path: https://filters.adtidy.org/android/filters/22_optimized.txt
      type: easylist
    
    - name: ABP 反广告过滤
      path: https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt

    - name: xndeye adblock list of easylist
      path: https://raw.githubusercontent.com/xndeye/adblock_list/refs/heads/release/easylist.txt
   
    - name: TT拒绝列表
      path: https://ghproxy.net/https://raw.githubusercontent.com/TTDNS/Cat/refs/heads/main/TT%E6%8B%92%E7%BB%9D%E5%88%97%E8%A1%A8%E6%B8%85%E5%8D%95%20(%E6%9B%B4%E6%96%B0%E4%B8%AD).txt
  
    - name: AdGuard Tracking Protection filter (Optimized)
      path: https://filters.adtidy.org/android/filters/3_optimized.txt
      type: easylist
 
    - name: Bypass Paywalls Clean filter
      path: https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt

    - name: 晴雅广告拦截规则重置版支持IOS
      path: http://rssv.cn/adguard/api.php?type=black
      
    - name: HyperADRules
      path: https://raw.githubusercontent.com/Lynricsy/HyperADRules/master/rules.txt

    - name: DD-AD
      path: https://raw.githubusercontent.com/afwfv/DD-AD/refs/heads/release/DD-AD.txt

    - name: 去广告规则，酷安反馈反馈
      path: https://raw.githubusercontent.com/qq5460168/666/refs/heads/master/rules.txt
        
    - name: AdRules 橘猫
      path: https://adrules.5iclub.us.kg/adblock.txt
    
    - name: NEO DEV HOST
      path: https://raw.githubusercontent.com/neodevpro/neodevhost/master/adblocker

    - name: jiekouAD
      path: https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt

    - name: DNS-Kuner
      path: https://raw.githubusercontent.com/Kuner-mw/DNS-Kuner/main/FilterRules/blacklist.txt 
        
    - name: 去广告规则，反馈🐧群请点击主页
      path: https://raw.githubusercontent.com/qq5460168/dangchu/main/black.txt

    - name: SM广告丟那吗hosts
      path: https://raw.githubusercontent.com/2Gardon/SM-Ad-FuckU-hosts/refs/heads/master/SMAdHosts
 
    - name: HaGeZi's Pro DNS Blocklist
      path: https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/adblock/pro.txt

    - name: 1Hosts (Lite)
      path: https://raw.githubusercontent.com/badmojr/1Hosts/refs/heads/master/Lite/adblock.txt
        
    - name: JiuYue_Rules
      path: https://rules.vlo.cc/dns/dns.txt    

    - name: DNS-Kuner Allow
      path: https://raw.githubusercontent.com/Kuner-mw/DNS-Kuner/main/FilterRules/allowlist.txt
      
    - name: AdguardFilter标准
      path: https://raw.githubusercontent.com/miaoermua/AdguardFilter/main/rule.txt

    - name: AdguardFilter黑名单
      path: https://raw.githubusercontent.com/miaoermua/AdguardFilter/main/bad_apple.txt
        
    - name: AdguardFilter白名单
      path: https://raw.githubusercontent.com/miaoermua/AdguardFilter/main/whitelist.txt       

  output:
  
    file_header: |
      wiz adblock list of ${type}
      Last Modified: ${date}
      Total Size: ${total}
      Homepage: https://github.com/ALLOVERleng/ad-filters-subscriber

   
    files:
      - name: easylist.txt     
        type: easylist         

      - name: dns.txt
        type: dns
        
      - name: dnsmasq.txt
        type: dnsmasq

      - name: clash.yaml
        type: clash

      - name: smartdns.txt
        type: smartdns

      - name: hosts.txt
        type: hosts

  config:

    #获取器配置
    fetcher:

      http:
        charset: UTF-8
        connect-timeout: 10s
        read-timeout: 30s
        write-timeout: 30s
        response-timeout: 30s
        buffer-size: 4KB

      local:
        charset: UTF-8
        buffer-size: 4KB

    #解析器配置
    parser:

      # 日志级别
      # 解析器日志将单独输出到 parser.log 文件
      log-level: debug

      # 建议最小规则长度
      # 一般来说越短的规则杀伤力越大，当超出此长度时，解析器会输出警告日志
      alert-length: 6

      # 解析器接受的最小规则长度，小于此长度的规则将被认定为无效规则 (0或空为不限制)
      min-length: 0

      # 解析器接受的最大规则长度，大于此长度的规则将被认定为无效规则 (0或空为不限制)
      max-length: 1024  # 默认为 1024 这也是 AdGuard 所支持的最大长度

      # 预期总规则数量
      # 此选项有助于提前分配内存以提高去重性能
      # 建议留空或设置一个保守值，不可过大
      expected: 200000

      dns-probe:
        enable: ture   # 是否启用
        parallel: 128    # 并发查询数

        # 多个之间具备优先级，为空则使用系统默认DNS
        provider:
          - host: 1.1.1.1
            port: 53 
          
          - host: 8.8.8.8

      # 排除域 (白名单)
      # 若规则目标域名在此列表中，则直接排除
      # ! 只适用可以被解析的规则
      excludes:
        - "edge.microsoft.com"
        - "public.gensparkspace.com"
        - "assets.msn.com"
